name: Docker Build
on:
  workflow_dispatch:
  schedule:
    # Run every day at midnight
    - cron: '0 0 * * *'
  push:
    paths:
      - docker/**/*
      - .github/workflows/docker.yml

jobs:
  build:
    name: Build
    # We need to make sure both the Dockerfile and the branch is main
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      actions: write
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: build
            file: docker/build.dockerfile
            runs-on: ubuntu-latest
          - name: cockroach
            file: docker/cockroach.dockerfile
            runs-on: ubuntu-latest
          - name: minio
            file: docker/minio.dockerfile
            runs-on: ubuntu-latest
          - name: nats
            file: docker/nats.dockerfile
            runs-on: ubuntu-latest
          - name: redis
            file: docker/redis.dockerfile
            runs-on: ubuntu-latest
          - name: backup
            file: docker/backup.dockerfile
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./${{ matrix.file }}
          push: true
          tags: |
            ghcr.io/scufflecloud/ci/${{ matrix.name }}:${{ github.sha }}
            ghcr.io/scufflecloud/ci/${{ matrix.name }}:latest
